### ISSUE TITLE
Create an intro

### ISSUE THREAD

**Issue by FiLoffs** [FiLoffs/homepage#4]
Add an intro about yourself: who are you, what is your strength, why are you here.

**Comment by maddy020** [comment]
Hey @FiLoffs 
I would love to contribute over the issue
Please elaborate what kind of issue is required

**Comment by FiLoffs** [comment]
I like programming and I have a plan to become a full stack .Net developer, I like to solve and complete tasks and projects, I am interested in learning and testing Web and Desktop technologies
